# Project information
site_name: "jangbi"
site_description: "."
site_url: "https://dure.one/jangbi"
repo_url: "https://github.com/dure-one/jangbi"
repo_name: "dure-one/jangbi"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md]
copyright: Copyright &copy; 2025 Dure.one
edit_uri: edit/main/docs/

# Documentation and theme
theme:
  name: 'material'
  logo: images/logo.png
  custom_dir: docs/.overrides

  features:
    - toc.integrate
    - toc.follow
    # navigation tabs multilang doesn't work without insider edition
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.suggest

  palette:
    ## Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  alternate:
    - name: "English "
      link: ""
      lang: en
    - name: "Korean"
      link: index.ko/
      lang: ko
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/dure-one
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Let us know how we can improve this page.

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "¤"
  - footnotes
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.extra
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  # - pymdownx.tabbed:
  #     alternate_style: true
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: shell
  - markdown-exec
  - section-index
  # - llmstxt:
  #     setions: []
  #     files:
  #       - output: llms-full.txt
  #       - inputs:
  #         - index.md
  - git-revision-date-localized:
      enabled: false
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: false
  - group:
      enabled: false
      plugins:
      - typeset
  - glightbox
  - i18n:
      languages:
        ko: "Korean"
        en: "English"
      default_language: 'en'
      no_translation:
        ko: "이 페이지는 아직 한글로 번역되지 않았습니다."
        en: "This page isn't translated to English yet."
      translate_nav:
        ko:
          "Overview": "개요"
          "Programs": "프로그램"
          "Changelog": "변경 로그"
          "Credits": "크레딧"
          "Contributing": "기여하기"
          "Code of Conduct": "행동 강령"
          "License": "라이선스"
          "Getting Started": "시작하기"
          "Gettingstarted": "시작하기"
          "Plugins": "플러그인"
          "jangbi": "장비"
          
nav:
  # Korean Tree
  - index.ko.md
  - gettingstarted.ko.md
  - Plugins:
    - plugins/index.ko.md
  # - recipes.ko.md
  # - troubleshooting.ko.md
  - changelog.ko.md
  - code_of_conduct.ko.md
  - contributing.ko.md
  - license.ko.md
  - credits.ko.md

  # English Tree
  - index.md
  - gettingstarted.md
  - Plugins:
    - plugins/index.md
    - plugins/net-darkstat.md
    - plugins/net-dnscryptproxy.md
    - plugins/net-dnsmasq.md
    - plugins/net-hostapd.md
    - plugins/net-hysteria.md
    - plugins/net-ifupdown.md
    - plugins/net-iptables.md
    - plugins/net-knockd.md
    - plugins/net-netplan.md
    - plugins/net-omnip.md
    - plugins/net-shoes.md
    - plugins/net-sshd.md
    - plugins/net-v2ray.md
    - plugins/net-xtables.md
    - plugins/os-aide.md
    - plugins/os-auditd.md
    - plugins/os-conf.md
    - plugins/os-disablebins.md
    - plugins/os-firmware.md
    - plugins/os-kparams.md
    - plugins/os-minmon.md
    - plugins/os-redis.md
    - plugins/os-sysctl.md
    - plugins/os-systemd.md
    - plugins/os-vector.md
  # - recipes.md
  - troubleshooting.md
  - development.md
  - changelog.md
  - code_of_conduct.md
  - contributing.md
  - license.md
  - credits.md
  
  - Dure.one: https://dure.one/"

  # # User Guide
  # - User Guide:
  #     - user/index.md
  #     - user/index.ko.md
  #     - Login:
  #       - login/index.md
  #       - login/index.ko.md
  #       - login/local_access.md
  #       - login/local_access.ko.md
  #     - Desktops:
  #       # Quickstart
  #       - user/create_desktop.md
  #       - user/create_desktop.ko.md
  #       # Viewers
  #       - user/viewers/viewers.md
  #       - user/viewers/viewers.ko.md
