# https://github.com/cfal/shoes/blob/master/CONFIG.md
# Listen on all IPv4 interfaces, port 443 (HTTPS)
# openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out some.crt -keyout some.key -subj "/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=localhost"
- address: 127.0.0.1:443
  transport: quic
  quic_settings:
    cert: /etc/shoes/some.crt
    key: /etc/shoes/some.key
    alpn_protocols:
    - h3
  protocol:
    type: hysteria2
    password: abc128459
  rules:
    - allow-all-direct