## \brief v2ray install configurations. <div style="text-align: right"> group:**postnet** | runtype:**minmon** | deps: **-** | port: **LO:1080**</div><br/>
## \desc 
## [V2Ray](https://v2fly.org/){:target="_blank"} is a platform for building proxies to bypass network restrictions and protect privacy.
# It provides automated installation, configuration management, and service control capabilities.
# V2Ray offers advanced routing capabilities for secure proxy and tunneling services.
## 
## # Jangbi Configs
## ```bash title="/opt/jangbi/.config"
## RUN_NET_V2RAY=1 # enable V2Ray proxy
## V2RAY_PORTS="LO:1080" # ports to listen, LO - localhost, 1080 - SOCKS port
## ```
## # Check if running
## ```bash title="bash command"
## $ ss -nltup|grep v2ray
## tcp   LISTEN 0      128        127.0.0.1:1080       0.0.0.0:*    users:(("v2ray",pid=12345,fd=3))
## $ pidof v2ray
## 12345
## ```
## # Current Configuration
## Current configuration is stored in `/etc/v2ray/`. it is generated by `net-v2ray configgen` command on install.
## You can edit it manually and not run install or configapply commands to keep current configurations.
## ```bash title="/etc/v2ray/config.json"
## --8<-- "./configs/v2ray/config.json"
## ```

# shellcheck shell=bash
cite about-plugin
about-plugin 'v2ray install configurations.'

function net-v2ray {
    about 'v2ray install configurations'
    group 'postnet'
    runtype 'minmon'
    deps ''
    param '1: command'
    param '2: params'
    example '$ net-v2ray subcommand'
    local PKGNAME="v2ray"
    local DMNNAME="net-v2ray"
    BASH_IT_LOG_PREFIX="net-v2ray: "
    V2RAY_PORTS="${V2RAY_PORTS:-"LO:1080"}"
    if _check_config_reload; then
        _root_only || exit 1
        _distname_check || exit 1
    fi

    if [[ $# -eq 1 ]] && [[ "$1" = "help" ]]; then
        __net-v2ray_help "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "install" ]]; then
        __net-v2ray_install "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "uninstall" ]]; then
        __net-v2ray_uninstall "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "download" ]]; then
        __net-v2ray_download "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "disable" ]]; then
        __net-v2ray_disable "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configgen" ]]; then
        __net-v2ray_configgen "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configapply" ]]; then
        __net-v2ray_configapply "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "check" ]]; then
        __net-v2ray_check "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "run" ]]; then
        __net-v2ray_run "$2"
    else
        __net-v2ray_help
    fi
}

## \usage net-v2ray help|install|uninstall|download|disable|configgen|configapply|check|run
## $ net-v2ray install - install V2Ray proxy platform
## $ net-v2ray uninstall - uninstall V2Ray
## $ net-v2ray download - download V2Ray package files to pkg dir
## $ net-v2ray disable - disable V2Ray plugin
## $ net-v2ray configgen - generate V2Ray configuration files
## $ net-v2ray configapply - apply V2Ray configuration files
## $ net-v2ray check - check V2Ray plugin status
## $ net-v2ray run - run V2Ray service
## $ net-v2ray help - show this help message
function __net-v2ray_help {
    echo -e "Usage: net-v2ray [COMMAND]\n"
    echo -e "Helper to v2ray install configurations.\n"
    echo -e "Commands:\n"
    echo "   help        Show this help message"
    echo "   install     Install v2ray"
    echo "   uninstall   Uninstall installed v2ray"
    echo "   download    Download pkg files to pkg dir"
    echo "   disable     Disable v2ray service"
    echo "   configgen   Configs Generator"
    echo "   configapply Apply Configs"
    echo "   check       Check vars available"
    echo "   run         run"
}

function __net-v2ray_install {
    log_debug "Installing ${DMNNAME}..."

    local filepat="./pkgs/v2ray-linux-*.zip"
    local tmpdir="/tmp/v2ray"
    rm -rf ${tmpdir} 1>/dev/null 2>&1
    mkdir -p ${tmpdir} 1>/dev/null 2>&1

    [[ $(find ${filepat}|wc -l) -lt 1 ]] && __net-v2ray_download
    # tar -zxvf ${filepat} -C ${tmpdir} --strip-components=1 1>/dev/null 2>&1
    unzip ${filepat} -d ${tmpdir} 1>/dev/null 2>&1
    if [[ ! -f /tmp/v2ray/v2ray ]]; then
        log_error "v2ray binary not found in package."
        return 1
    fi

    # copy to /usr/local/v2ray and link to /usr/sbin
    cp ${tmpdir}/v2ray /usr/sbin/v2ray
    chmod 755 /usr/sbin/v2ray
    # rm -rf ${tmpdir} 1>/dev/null 2>&1
    touch /var/log/v2ray.log

    if ! __net-v2ray_configgen; then # if gen config is different do apply
        __net-v2ray_configapply
        rm -rf ${tmpdir}
    fi
    mkdir -p /var/log/v2ray
}

function __net-v2ray_configgen { # config generator and diff
    log_debug "Generating config for ${DMNNAME}..."
    rm -rf /tmp/${PKGNAME} 1>/dev/null 2>&1
    mkdir -p /tmp/${PKGNAME} /etc/${PKGNAME} 1>/dev/null 2>&1

    unzip ${filepat} -d ${tmpdir} 1>/dev/null 2>&1
    rm -rf /tmp/v2ray/v2ray /tmp/v2ray/systemd
    mv /tmp/v2ray/config.json /tmp/v2ray/config.json.default
    cp ./configs/${PKGNAME}/* /tmp/${PKGNAME}/
    
    # diff check
    diff -Naur /etc/${PKGNAME} /tmp/${PKGNAME} > /tmp/${PKGNAME}.diff
    [[ $(stat -c %s /tmp/${PKGNAME}.diff) = 0 ]] && return 0 || return 1
}

function __net-v2ray_configapply {
    [[ ! -f /tmp/${PKGNAME}.diff ]] && log_error "/tmp/${PKGNAME}.diff file doesnt exist. please run configgen."
    log_debug "Applying config ${DMNNAME}..."
    local dtnow=$(date +%Y%m%d_%H%M%S)
    [[ -d "/etc/${PKGNAME}" ]] && cp -rf "/etc/${PKGNAME}" "/etc/.${PKGNAME}.${dtnow}"
    pushd /etc/${PKGNAME} 1>/dev/null 2>&1
    patch -i /tmp/${PKGNAME}.diff
    popd 1>/dev/null 2>&1
    rm /tmp/${PKGNAME}.diff
    return 0
}

function __net-v2ray_download {
    log_debug "Downloading ${DMNNAME}..."
    arch1_=$(dpkg --print-architecture)
    arch1=${3:-${arch1_}}
    [[ ${arch1} == "amd64" ]] && comparch="-64-"
    [[ ${arch1} == "arm64" ]] && comparch="-arm64-v8a-"

    _download_github_pkgs v2fly/v2ray-core v2ray-linux-*.zip "${comparch}" || log_error "${DMNNAME} download failed."
    return 0
}

function __net-v2ray_disable {
    log_debug "Disabling ${DMNNAME}..."
    pidof v2ray | xargs kill -9 2>/dev/null
    return 0
}

function __net-v2ray_uninstall {
    log_debug "Uninstalling ${DMNNAME}..."
    pidof v2ray | xargs kill -9 2>/dev/null
    rm -rf /usr/sbin/v2ray
}

function __net-v2ray_check { # running_status 0 installed, running_status 5 can install, running_status 10 can't install, 20 skip
    running_status=0
    log_debug "Checking ${DMNNAME}..."

    # check package file exists
    [[ $(find ./pkgs/v2ray-linux-*.zip|wc -l) -lt 1 ]] && \
        log_info "v2ray package file does not exist." && [[ $running_status -lt 15 ]] && running_status=15
    # check global variable
    [[ -z ${RUN_NET_V2RAY} ]] && \
        log_info "RUN_NET_V2RAY variable is not set." && __net-v2ray_disable && [[ $running_status -lt 10 ]] && running_status=10
    [[ ${RUN_NET_V2RAY} != 1 ]] && \
        log_info "RUN_NET_V2RAY is not enabled." && [[ $running_status -lt 20 ]] && running_status=20
    # check package installed
    [[ $(which v2ray|wc -l) -lt 1 ]] && \
        log_info "v2ray is not installed." && [[ $running_status -lt 5 ]] && running_status=5
    # check if running
    [[ $(pidof v2ray) -gt 0 ]] && \
        log_info "v2ray is running." && [[ $running_status -lt 0 ]] && running_status=0

    return 0
}

function __net-v2ray_run {
    log_debug "Running ${DMNNAME}..."
    
    pidof v2ray | xargs kill &>/dev/null
    
    log_debug "Starting v2ray" 
    v2ray run --config=/etc/v2ray/config.json &
    
    pidof v2ray && return 0 || \
        log_error "v2ray failed to run." && return 0
}

complete -F _blank net-v2ray