## \brief Suricata IDS/IPS install configurations. <div style="text-align: right"> group:**postnet** | runtype:**minmon** | deps: **-** | port: **-**</div><br/>
## \desc
## [Suricata](https://suricata.io/){:target="_blank"} is a high-performance Network IDS, IPS and Network Security Monitoring engine.
# It provides real-time intrusion detection, inline intrusion prevention, and network security monitoring.
# Suricata analyzes network traffic to detect threats using signature-based and anomaly-based detection methods.
##
## # Jangbi Configs
## ```bash title="/opt/jangbi/.config"
## RUN_NET_SURICATA=1 # enable Suricata IDS/IPS
## SURICATA_MODE="IDS" # IDS (monitoring) or IPS (prevention) mode
## ```
## # Check if running
## ```bash title="bash command"
## $ pidof suricata
## 12345
## $ tail -f /var/log/suricata/fast.log
## [**] [1:2100498:7] GPL ATTACK_RESPONSE id check returned root [**]
## ```
## # Current Configuration
## Current configuration is stored in `/etc/suricata/`. it is generated by `net-suricata configgen` command on install.
## You can edit it manually and not run install or configapply commands to keep current configurations.
## ```yaml title="/etc/suricata/suricata.yaml"
## --8<-- "./configs/suricata/suricata.yaml.sample"
## ```

# shellcheck shell=bash
cite about-plugin
about-plugin 'Suricata IDS/IPS install configurations.'

function net-suricata {
    about 'Suricata IDS/IPS install configurations'
    group 'postnet'
    runtype 'minmon'
    deps  ''
    param '1: command'
    param '2: params'
    example '$ net-suricata subcommand'
    local PKGNAME="suricata"
    local DMNNAME="net-suricata"
    BASH_IT_LOG_PREFIX="net-suricata: "
    SURICATA_MODE="${SURICATA_MODE:-"IDS"}"
    if _check_config_reload; then
        _root_only || exit 1
        _distname_check || exit 1
    fi

    if [[ $# -eq 1 ]] && [[ "$1" = "help" ]]; then
        __net-suricata_help "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "install" ]]; then
        __net-suricata_install "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "uninstall" ]]; then
        __net-suricata_uninstall "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "download" ]]; then
        __net-suricata_download "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "disable" ]]; then
        __net-suricata_disable "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configgen" ]]; then
        __net-suricata_configgen "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configapply" ]]; then
        __net-suricata_configapply "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "check" ]]; then
        __net-suricata_check "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "run" ]]; then
        __net-suricata_run "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "updaterules" ]]; then
        __net-suricata_update_rules "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "pkglist" ]]; then
        __net-suricata_pkglist
    else
        __net-suricata_help
    fi
}

## \usage net-suricata help|install|uninstall|download|disable|configgen|configapply|check|run|updaterules
## $ net-suricata install - install Suricata IDS/IPS
## $ net-suricata uninstall - uninstall Suricata
## $ net-suricata download - download Suricata package files to pkg dir
## $ net-suricata disable - disable Suricata plugin
## $ net-suricata configgen - generate Suricata configuration files
## $ net-suricata configapply - apply Suricata configuration files
## $ net-suricata check - check Suricata plugin status
## $ net-suricata run - run Suricata service
## $ net-suricata updaterules - update Suricata rules using suricata-update
## $ net-suricata help - show this help message
function __net-suricata_help {
    echo -e "Usage: net-suricata [COMMAND]\n"
    echo -e "Helper to Suricata IDS/IPS install configurations.\n"
    echo -e "Commands:\n"
    echo "   help        Show this help message"
    echo "   install     Install Suricata"
    echo "   uninstall   Uninstall installed Suricata"
    echo "   download    Download pkg files to pkg dir"
    echo "   disable     Disable Suricata"
    echo "   configgen   Configs Generator"
    echo "   configapply Apply Configs"
    echo "   check       Check vars available"
    echo "   run         Run tasks"
    echo "   updaterules Update Suricata rules"
}

function __net-suricata_install {
    log_debug "Installing ${DMNNAME}..."

    # Backup existing config before installation
    local dtnow=$(date +%Y%m%d_%H%M%S)
    if [[ -d "/etc/${PKGNAME}" ]]; then
        log_debug "Backing up existing ${PKGNAME} config..."
        cp -rf "/etc/${PKGNAME}" "/etc/.${PKGNAME}.${dtnow}"
    fi

    export DEBIAN_FRONTEND=noninteractive
    if [[ ${INTERNET_AVAIL} -gt 0 ]]; then
        [[ $(find /etc/apt/sources.list.d|grep -c "extrepo_debian_official") -lt 1 ]] && extrepo enable debian_official
        [[ $(stat /var/lib/apt/lists -c "%X") -lt $(date -d "1 day ago" +%s) ]] && apt update -qy
        apt install -qy ${PKGNAME} || log_error "${DMNNAME} online install failed."
    else
        local filepat="./pkgs/${PKGNAME}*.deb"
        local pkglist="./pkgs/${PKGNAME}.pkgs"
        [[ $(find ${filepat} 2>/dev/null|wc -l) -lt 1 ]] && __net-suricata_download
        pkgslist_down=()
        while read -r pkg; do
            [[ $pkg ]] && pkgslist_down+=("./pkgs/${pkg}*.deb")
        done < ${pkglist}
        # shellcheck disable=SC2068
        apt install -qy ${pkgslist_down[@]} || log_error "${DMNNAME} offline install failed."
    fi

    # Create log directories
    mkdir -p /var/log/suricata
    chmod 750 /var/log/suricata

    if ! __net-suricata_configgen; then # if gen config is different do apply
        __net-suricata_configapply
        rm -rf /tmp/${PKGNAME}
    fi
}

function __net-suricata_uninstall {
    log_debug "Uninstalling ${DMNNAME}..."
    pidof suricata | xargs kill -9 2>/dev/null
    apt purge -qy suricata
}

function __net-suricata_download {
    log_debug "Downloading ${DMNNAME}..."
    _download_apt_pkgs "suricata" || log_error "${DMNNAME} download failed."
    return 0
}

function __net-suricata_pkglist {
    echo "suricata"
}

function __net-suricata_disable {
    log_debug "Disabling ${DMNNAME}..."
    pidof suricata | xargs kill -9 2>/dev/null
    return 0
}

function __net-suricata_configgen { # config generator and diff
    log_debug "Generating config for ${DMNNAME}..."
    rm -rf /tmp/${PKGNAME} 1>/dev/null 2>&1
    mkdir -p /tmp/${PKGNAME} /etc/${PKGNAME} 1>/dev/null 2>&1

    # Copy base config if exists
    if [[ -d ./configs/${PKGNAME} ]]; then
        cp -r ./configs/${PKGNAME}/* /tmp/${PKGNAME}/
    fi

    __net-suricata_generate_config

    # diff check
    diff -Naur /etc/${PKGNAME} /tmp/${PKGNAME} > /tmp/${PKGNAME}.diff
    [[ $(stat -c %s /tmp/${PKGNAME}.diff) = 0 ]] && return 0 || return 1
}

function __net-suricata_configapply {
    [[ ! -f /tmp/${PKGNAME}.diff ]] && log_error "/tmp/${PKGNAME}.diff file doesnt exist. please run configgen."
    log_debug "Applying config ${DMNNAME}..."

    # Backup existing config
    local dtnow=$(date +%Y%m%d_%H%M%S)
    [[ -d "/etc/${PKGNAME}" ]] && cp -rf "/etc/${PKGNAME}" "/etc/.${PKGNAME}.${dtnow}"

    # Instead of using patch, directly copy only the suricata.yaml file
    # This preserves existing rule files and only updates the main config
    if [[ -f /tmp/${PKGNAME}/suricata.yaml ]]; then
        cp /tmp/${PKGNAME}/suricata.yaml /etc/${PKGNAME}/suricata.yaml
        chmod 600 /etc/${PKGNAME}/suricata.yaml
    fi

    rm /tmp/${PKGNAME}.diff
    return 0
}

function __net-suricata_check { # running_status: 0 running, 1 installed, running_status 5 can install, running_status 10 can't install, 20 skip
    running_status=0
    log_check_ok "Checking ${DMNNAME}..."

    # check package file exists
    [[ $(find ./pkgs/${PKGNAME}*.pkgs 2>/dev/null|wc -l) -lt 1 ]] && \
        log_check "${PKGNAME} package file does not exist." && [[ $running_status -lt 15 ]] && running_status=15
    # check global variable
    [[ -z ${RUN_NET_SURICATA} ]] && \
        log_error "RUN_NET_SURICATA variable is not set." && [[ $running_status -lt 10 ]] && running_status=10
    [[ ${RUN_NET_SURICATA} != 1 ]] && \
        log_error "RUN_NET_SURICATA is not enabled." && __net-suricata_disable && [[ $running_status -lt 20 ]] && running_status=20
    # check package installed
    [[ $(dpkg -l|awk '{print $2}'|grep -c "suricata") -lt 1 ]] && \
        log_check "suricata is not installed." && [[ $running_status -lt 5 ]] && running_status=5
    # check if running
    [[ $(pidof suricata) -gt 0 ]] && \
        log_check_ok "suricata is running." && [[ $running_status -lt 1 ]] && running_status=1

    return 0
}

function __net-suricata_run {
    log_debug "Running ${DMNNAME}..."

    # Update rules before running
    __net-suricata_update_rules

    # Kill existing process
    pidof suricata | xargs kill -9 2>/dev/null

    # Determine interface to monitor
    local monitor_inf=""
    if [[ -n ${JB_WANINF} ]]; then
        monitor_inf=${JB_WANINF}
    elif [[ -n ${JB_LANINF} ]]; then
        monitor_inf=${JB_LANINF}
    else
        # Fallback to first non-loopback interface
        monitor_inf=$(ip -o link show | awk -F': ' '$2 !~ /^lo$/ {print $2; exit}')
    fi

    if [[ -z ${monitor_inf} ]]; then
        log_error "No network interface found for Suricata monitoring."
        return 1
    fi

    log_debug "Starting Suricata on interface ${monitor_inf} in ${SURICATA_MODE} mode..."

    # Run Suricata in background
    if [[ ${SURICATA_MODE} == "IPS" ]]; then
        # IPS mode (inline/prevention)
        suricata -c /etc/suricata/suricata.yaml -i ${monitor_inf} --init-errors-fatal -D 1>>/var/log/suricata/suricata.log 2>&1
    else
        # IDS mode (monitoring only)
        suricata -c /etc/suricata/suricata.yaml -i ${monitor_inf} --init-errors-fatal -D 1>>/var/log/suricata/suricata.log 2>&1
    fi

    sleep 2
    pidof suricata && return 0 || \
        log_error "suricata failed to run." && return 1
}

function __net-suricata_update_rules {
    log_debug "Updating Suricata rules..."

    # Check if internet is available by trying to reach a known host
    if ping -c 1 -W 2 1.1.1.1 &>/dev/null || ping -c 1 -W 2 8.8.8.8 &>/dev/null; then
        # Use suricata-update to download and install latest rules
        if command -v suricata-update &> /dev/null; then
            log_debug "Running suricata-update..."
            suricata-update 1>>/var/log/suricata/update.log 2>&1 || \
                log_error "suricata-update failed."
        else
            log_debug "suricata-update command not found, skipping rules update."
        fi
    else
        log_debug "Internet not available, skipping rules update."
    fi
}

function __net-suricata_generate_config {
    log_debug "Generating Suricata configuration..."

    # Determine monitoring interface like net-ifupdown does
    local monitor_inf=""
    if [[ -n ${JB_WANINF} ]]; then
        monitor_inf=${JB_WANINF}
    elif [[ -n ${JB_LANINF} ]]; then
        monitor_inf=${JB_LANINF}
    else
        # Auto-select first non-loopback interface
        local dure_infs=($(cat /proc/net/dev | awk '{ print $1 }' | grep : | grep -v lo: | sed 's/:$//'))
        if [[ ${#dure_infs[@]} -gt 0 ]]; then
            monitor_inf=${dure_infs[0]}
        else
            monitor_inf="eth0"
        fi
    fi

    log_debug "Configuring Suricata for interface: ${monitor_inf}"

    # Get network ranges for HOME_NET
    local home_nets=""
    [[ -n ${JB_LAN} ]] && home_nets="${JB_LAN}"
    [[ -n ${JB_WLAN} ]] && home_nets="${home_nets:+${home_nets},}${JB_WLAN}"
    [[ -z ${home_nets} ]] && home_nets="192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"

    # Create basic suricata.yaml if it doesn't exist in /tmp
    if [[ ! -f /tmp/${PKGNAME}/suricata.yaml ]]; then
        # Try to copy from system default, from configs dir, or from sample locations
        if [[ -f /etc/suricata/suricata.yaml ]]; then
            cp /etc/suricata/suricata.yaml /tmp/${PKGNAME}/suricata.yaml
        elif [[ -f ./configs/${PKGNAME}/suricata.yaml ]]; then
            cp ./configs/${PKGNAME}/suricata.yaml /tmp/${PKGNAME}/suricata.yaml
        elif [[ -f /usr/share/suricata/suricata.yaml ]]; then
            cp /usr/share/suricata/suricata.yaml /tmp/${PKGNAME}/suricata.yaml
        elif [[ -f /usr/share/doc/suricata/examples/suricata.yaml ]]; then
            cp /usr/share/doc/suricata/examples/suricata.yaml /tmp/${PKGNAME}/suricata.yaml
        else
            log_error "Default suricata.yaml not found in any location. Suricata package may not be properly installed."
            log_error "Tried: /etc/suricata, ./configs/suricata, /usr/share/suricata, /usr/share/doc/suricata/examples"
            return 1
        fi
    fi

    # Update interface and HOME_NET in config
    sed -i "s|interface:.*|interface: ${monitor_inf}|g" /tmp/${PKGNAME}/suricata.yaml
    sed -i "s|HOME_NET:.*|HOME_NET: \"[${home_nets}]\"|g" /tmp/${PKGNAME}/suricata.yaml

    # Set rule path
    sed -i "s|default-rule-path:.*|default-rule-path: /var/lib/suricata/rules|g" /tmp/${PKGNAME}/suricata.yaml

    log_debug "Suricata config generated for ${monitor_inf} with HOME_NET=${home_nets}"
}

complete -F _blank net-suricata
