## \brief aide install configurations. <div style="text-align: right"> group:**prenet** | runtype:**none** | deps: **-** | port: **-**</div><br/>
## \desc 
## [AIDE](https://aide.github.io/){:target="_blank"} (Advanced Intrusion Detection Environment) monitors file system changes.
# It provides automated installation, configuration management, checkpoint creation, and integrity checking capabilities.
# AIDE monitors file system changes and can detect unauthorized modifications to critical system files.
## 
## # Jangbi Configs
## ```bash title="/opt/jangbi/.config"
## RUN_OS_AIDE=1 # enable aide file integrity monitoring
## ```
## # Check if running
## ```bash title="bash command"
## $ aide --check
## AIDE found differences between database and filesystem!!
## $ ls -la /var/lib/aide/
## -rw-r--r-- 1 root root aide.db
## ```
## # Current Configuration
## Current configuration is stored in `/etc/aide/`. it is generated by `os-aide configgen` command on install.
## You can edit it manually and not run install or configapply commands to keep current configurations.
## ```bash title="/etc/aide/aide.conf"
## --8<-- "./configs/aide/aide.minimal.conf"
## ```

# shellcheck shell=bash
cite about-plugin
about-plugin 'aide install configurations.'

function os-aide {
    about 'aide install configurations'
    group 'prenet'
    runtype 'none' # systemd, minmon, none
    deps  ''
    param '1: command'
    param '2: params'
    example '$ os-aide subcommand'
    local PKGNAME="aide"
    local DMNNAME="os-aide"
    BASH_IT_LOG_PREFIX="os-aide: "
    # AIDE_PORTS="${AIDE_PORTS:-""}"
    if _check_config_reload; then
        _root_only || exit 1
        _distname_check || exit 1
    fi

    if [[ $# -eq 1 ]] && [[ "$1" = "help" ]]; then
        __os-aide_help "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "install" ]]; then
        __os-aide_install "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "uninstall" ]]; then
        __os-aide_uninstall "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "download" ]]; then
        __os-aide_download "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "disable" ]]; then
        __os-aide_disable "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configgen" ]]; then
        __os-aide_configgen "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "configapply" ]]; then
        __os-aide_configapply "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "check" ]]; then
        __os-aide_check "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "run" ]]; then
        __os-aide_run "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "checkpoint" ]]; then
        __os-aide_checkpoint "$2"
    elif [[ $# -eq 1 ]] && [[ "$1" = "pkglist" ]]; then
        __os-aide_pkglist
    else
        __os-aide_help
    fi
}

## \usage os-aide help|install|uninstall|download|disable|configgen|configapply|check|run|checkpoint
## $ os-aide install - install AIDE file integrity monitoring
## $ os-aide uninstall - uninstall AIDE
## $ os-aide download - download AIDE package files to pkg dir
## $ os-aide disable - disable AIDE plugin
## $ os-aide configgen - generate AIDE configuration files
## $ os-aide configapply - apply AIDE configuration files
## $ os-aide check - check AIDE plugin status
## $ os-aide run - run AIDE integrity check
## $ os-aide checkpoint - create new AIDE database checkpoint
## $ os-aide help - show this help message
function __os-aide_help {
    echo -e "Usage: os-aide [COMMAND]\n"
    echo -e "Helper to aide install configurations.\n"
    echo -e "Commands:\n"
    echo "   help        Show this help message"
    echo "   install     Install os aide"
    echo "   uninstall   Uninstall installed aide"
    echo "   download    Download pkg files to pkg dir"
    echo "   disable     Disable aide"
    echo "   configgen   Configs Generator"
    echo "   configapply Apply Configs"
    echo "   check       Check vars available"
    echo "   run         Run tasks"
    echo "   checkpoint  Make new checkpoint"
}

function __os-aide_install {
    log_debug "Installing ${DMNNAME}..."
    export DEBIAN_FRONTEND=noninteractive
    mkdir -p /etc/aide /var/lib/aide /var/log/aide

    # Default to offline install if INTERNET_AVAIL is not set
    local internet_avail="${INTERNET_AVAIL:-0}"

    if [[ ${internet_avail} -gt 0 ]]; then
        [[ $(find /etc/apt/sources.list.d|grep -c "extrepo_debian_official") -lt 1 ]] && extrepo enable debian_official
        [[ $(stat /var/lib/apt/lists -c "%X") -lt $(date -d "1 day ago" +%s) ]] && apt update -qy
        if ! apt install -qy aide; then
            log_error "${DMNNAME} online install failed."
            return 1
        fi
    else
        local filepat="./pkgs/aide*.deb"
        local pkglist="./pkgs/aide.pkgs"

        # Get system's primary architecture
        local sys_arch=$(dpkg --print-architecture)

        # Check if any aide packages exist, if not download them
        [[ $(find ${filepat} 2>/dev/null|wc -l) -lt 1 ]] && apt update -qy && __os-aide_download

        pkgslist_down=()
        # Package list is space-separated on one line, convert to array
        # Remove duplicates by using associative array
        declare -A seen_pkgs
        while read -r pkg; do
            if [[ -n "$pkg" ]]; then
                # Handle architecture-specific packages (e.g., pkg:i386)
                local pkgname="${pkg%%:*}"  # Remove :arch suffix
                local pkgarch="${pkg#*:}"   # Extract arch if present

                if [[ "$pkgarch" != "$pkg" ]] && [[ -n "$pkgarch" ]]; then
                    # Package has architecture suffix
                    # Only include if it matches system architecture
                    if [[ "$pkgarch" == "$sys_arch" ]]; then
                        for file in ./pkgs/${pkgname}_*_${pkgarch}.deb; do
                            if [[ -f "$file" ]] && [[ -z "${seen_pkgs[$file]}" ]]; then
                                pkgslist_down+=("$file")
                                seen_pkgs[$file]=1
                            fi
                        done
                    else
                        log_debug "Skipping foreign architecture package: ${pkg} (system is ${sys_arch})"
                    fi
                else
                    # No architecture suffix, find packages matching system arch
                    for file in ./pkgs/${pkgname}_*_${sys_arch}.deb; do
                        if [[ -f "$file" ]] && [[ -z "${seen_pkgs[$file]}" ]]; then
                            pkgslist_down+=("$file")
                            seen_pkgs[$file]=1
                        fi
                    done
                    # If no arch-specific package found, try all-architecture package
                    if [[ -z "${seen_pkgs[*]}" ]]; then
                        for file in ./pkgs/${pkgname}_*_all.deb; do
                            if [[ -f "$file" ]] && [[ -z "${seen_pkgs[$file]}" ]]; then
                                pkgslist_down+=("$file")
                                seen_pkgs[$file]=1
                            fi
                        done
                    fi
                fi
            fi
        done < <(tr ' ' '\n' < ${pkglist})

        if [[ ${#pkgslist_down[@]} -eq 0 ]]; then
            log_warning "No package files found for architecture ${sys_arch}. Falling back to online installation."
            [[ $(find /etc/apt/sources.list.d|grep -c "extrepo_debian_official") -lt 1 ]] && extrepo enable debian_official
            [[ $(stat /var/lib/apt/lists -c "%X") -lt $(date -d "1 day ago" +%s) ]] && apt update -qy
            if ! apt install -qy aide; then
                log_error "${DMNNAME} online install failed."
                return 1
            fi
            # Skip the offline install path below
            pkgslist_down=()
        fi

        # Only attempt offline install if we have packages
        if [[ ${#pkgslist_down[@]} -gt 0 ]]; then
            log_debug "Installing ${#pkgslist_down[@]} package(s): ${pkgslist_down[*]}"

            # Install dependencies first if needed, then install aide
            # shellcheck disable=SC2068
            apt install -qy ${pkgslist_down[@]}
            local apt_exit=$?

            if [[ $apt_exit -ne 0 ]]; then
                log_error "${DMNNAME} offline install failed (apt exit code: ${apt_exit}). Packages: ${pkgslist_down[*]}"
                return 1
            fi
        fi
    fi

    # Verify installation
    if ! command -v aide &>/dev/null; then
        log_error "aide command not found after installation."
        return 1
    fi

    if ! __os-aide_configgen; then # if gen config is different do apply
        __os-aide_configapply
        rm -rf /tmp/${PKGNAME}
    fi

    # Initialize AIDE database
    log_debug "Initializing AIDE database..."
    if aide --init --config=/etc/aide/aide.minimal.conf 2>/dev/null; then
        cp /var/lib/aide/aide.minimal.db.new.gz /var/lib/aide/aide.minimal.db.gz
        log_info "AIDE database initialized successfully."
    else
        log_error "Failed to initialize AIDE database."
        return 1
    fi
    return 0
}

function __os-aide_uninstall { 
    log_debug "Uninstalling ${DMNNAME}..."
    apt purge -yq aide
}

function __os-aide_download {
    log_debug "Downloading ${DMNNAME}..."
    _download_apt_pkgs "aide" || log_error "${DMNNAME} download failed."
    return 0
}

function __os-aide_pkglist {
    echo "aide"
}

function __os-aide_disable {
    log_debug "Disabling ${DMNNAME}..."
    :
}

function __os-aide_configgen { # config generator and diff
    log_debug "Generating config for ${DMNNAME}..."
    rm -rf /tmp/${PKGNAME} 1>/dev/null 2>&1
    mkdir -p /tmp/${PKGNAME} /etc/${PKGNAME} 1>/dev/null 2>&1
    cp ./configs/${PKGNAME}/* /tmp/${PKGNAME}/
    diff -Naur /etc/${PKGNAME} /tmp/${PKGNAME} > /tmp/${PKGNAME}.diff
    [[ $(stat -c %s /tmp/${PKGNAME}.diff) = 0 ]] && return 0 || return 1
}

function __os-aide_configapply {
    [[ ! -f /tmp/${PKGNAME}.diff ]] && log_error "/tmp/${PKGNAME}.diff file doesnt exist. please run configgen."
    log_debug "Applying config ${DMNNAME}..."
    local dtnow=$(date +%Y%m%d_%H%M%S)
    [[ -d "/etc/${PKGNAME}" ]] && cp -rf "/etc/${PKGNAME}" "/etc/.${PKGNAME}.${dtnow}"
    pushd /etc/${PKGNAME} 1>/dev/null 2>&1
    patch -i /tmp/${PKGNAME}.diff
    popd 1>/dev/null 2>&1
    rm /tmp/${PKGNAME}.diff
    return 0
}

function __os-aide_check { # running_status: 0 running, 1 installed, running_status 5 can install, running_status 10 can't install, 20 skip
    running_status=0
    log_debug "Checking ${DMNNAME}..."

    # check package file exists
    [[ $(find ./pkgs/${PKGNAME}*.pkgs|wc -l) -lt 1 ]] && \
        log_info "${PKGNAME} package file does not exist." && [[ $running_status -lt 15 ]] && running_status=15
    # check global variable
    [[ -z ${RUN_OS_AIDE} ]] && \
        log_error "RUN_OS_AIDE variable is not set." && [[ $running_status -lt 10 ]] && running_status=10
    [[ ${RUN_OS_AIDE} != 1 ]] && \
        log_error "RUN_OS_AIDE is not enabled." && [[ $running_status -lt 20 ]] && running_status=20
    # check package aide
    [[ $(dpkg -l|awk '{print $2}'|grep -c "aide") -lt 1 ]] && \
        log_info "aide is not installed." && [[ $running_status -lt 5 ]] && running_status=5
    # check if running
    [[ $(pidof aide) -gt 0 ]] && \
        log_info "aide is running." && [[ $running_status -lt 1 ]] && running_status=1

    return 0
}

function __os-aide_run {
    # aide minimal check for first run
    if ! command -v aide &>/dev/null; then
        log_error "aide command not found. Please install aide first."
        return 1
    fi

    local dtnow=$(date +%Y%m%d_%H%M%S)
    mkdir -p /var/log/aide

    # Run in background and capture all output
    # Note: AIDE exit codes: 0=no changes, 1=changes detected, 2+=errors
    aide --check --config=/etc/aide/aide.minimal.conf >"/var/log/aide/log_${dtnow}.log" 2>&1 &
    local aide_pid=$!

    log_info "AIDE check started in background (PID: ${aide_pid}), log: /var/log/aide/log_${dtnow}.log"
    log_info "Note: AIDE exit code 1 means changes detected (expected), not an error."
    return 0
}

complete -F _blank os-aide

function __os-aide_checkpoint {
    if ! command -v aide &>/dev/null; then
        log_error "aide command not found. Please install aide first."
        return 1
    fi

    log_debug "Make new checkpoint for os-aide."
    local dtnow=$(date +%Y%m%d_%H%M%S)
    mkdir -p /tmp/aidecp /var/log/aide/checkpoints

    # Run AIDE check, capturing exit code
    # Exit codes: 0=no changes, 1=changes detected, 2+=errors
    aide --check --config=/etc/aide/aide.minimal.conf >/tmp/aidecp/aide_${dtnow}.log 2>&1
    local aide_exit=$?

    # Save the check log
    cp /tmp/aidecp/aide_${dtnow}.log /var/log/aide/checkpoints/

    # Update database if check completed (exit 0 or 1)
    if [[ ${aide_exit} -le 1 ]]; then
        if [[ -f /var/lib/aide/aide.minimal.db.new.gz ]]; then
            cp /var/lib/aide/aide.minimal.db.new.gz /var/lib/aide/aide.minimal.db.gz
            log_info "AIDE checkpoint created: /var/log/aide/checkpoints/aide_${dtnow}.log"
            [[ ${aide_exit} -eq 1 ]] && log_info "Changes detected and database updated."
            [[ ${aide_exit} -eq 0 ]] && log_info "No changes detected."
        else
            log_error "AIDE database file not found: /var/lib/aide/aide.minimal.db.new.gz"
            return 1
        fi
    else
        log_error "AIDE check failed with exit code ${aide_exit}. Check log: /var/log/aide/checkpoints/aide_${dtnow}.log"
        return 1
    fi

    rm -rf /tmp/aidecp
    return 0
}