# https://github.com/nektos/act
# https://www.summerbud.org/dev-notes/run-playwright-integration-test-in-docker-containers
# https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/.github/workflows/tests.yaml
name: integrationtest

# on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repos
        run: sudo apt-get update -y

      - name: Install apt packages
        run: sudo apt-get install -y build-essential cmake git uuid-dev faketime locales python3 curl gcovr ninja-build

      - name: Check out this repository
        uses: actions/checkout@v4.1.6

      - name: Install prerequisites
        run: apt install -qy ipcalc-ng git

      - name: Test project
        run: cd test && ./test.sh

  # MacOS tests do not run in Docker, and use the actions-rs Rust installaction
  tests-macos-12:
    needs: coverage
    name: tests (Mac OS 12.latest)
    if: false # see #3242
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test MacOS
        run: bash test/scripts/test_macos.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests-macos-13:
    needs: coverage
    name: tests (Mac OS 13.latest)
    if: false
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Test MacOS
        run: bash test/scripts/test_macos.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    needs: coverage
    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: "Fedora 40"
          #   runner: ubuntu-latest
          #   dockerfile: fedora40
          # - name: "Fedora 41"
          #   runner: ubuntu-latest
          #   dockerfile: fedora41
          - name: "Debian Stable"
            runner: ubuntu-latest
            dockerfile: debianstable
          - name: "Debian Testing"
            runner: ubuntu-latest
            dockerfile: debiantesting
          # - name: "Ubuntu 20.04"
          #   runner: ubuntu-latest
          #   dockerfile: ubuntu2004
          # - name: "Ubuntu 22.04"
          #   runner: ubuntu-latest
          #   dockerfile: ubuntu2204
          # - name: "OpenSUSE Tumbleweed (Rolling)"
          #   runner: ubuntu-latest
          #   dockerfile: opensuse
          # - name: "Archlinux Base (Rolling)"
          #   runner: ubuntu-latest
          #   dockerfile: arch
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.continue-on-error == true }}
    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.name }}
        env:
          DOCKER_REGISTRY: docker.pkg.github.com
          DOCKER_CACHE_IMAGE: docker.pkg.github.com/${{ github.repository }}/taskwarrior_cache
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.dockerfile }}
        run: docker compose build test-${{ env.CONTAINER }}

      - name: Test ${{ matrix.name }}
        run: docker compose run test-${{ env.CONTAINER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.dockerfile }}